### PR TITLE
Avoid Type Widening

### PR DESCRIPTION
**Pull request by golnazmes**
adding the register method to solve issue #4

### CODE REVIEW

**Review by andy-amii — CHANGES_REQUESTED** [review]
This looks perfect! We should go ahead and start adding some small testing infrastructure.

For a change like this, a really brief integration test is perfect. Basically:
1. Make a checkpoint object
2. Register a builder function to the checkpoint
3. `assert` that you can get the data from the checkpoint
4. Delete the checkpoint and rebuild
5. `assert` that you can get the data again

Very similar to the acceptance test, though we can remove some of the boilerplate.

**Comment by andy-amii** [comment]
One other minor change: there are some duplicated commits in this PR. This is a common occurrence for projects using a `git rebase` workflow and is one of downsides to this particular workflow. Usually easy enough to fix:
```bash
git fetch upstream main
git rebase -i upstream/main
```
these commands say:
1. Download the changes from the upstream repo's main branch (amii-open-source/recommence), but don't do anything with them
2. Take those changes and rebase my current branch to be on top of those changes

When you do this, you will likely see a bunch of extra commits in the interactive rebase:
```
pick feat: add initial checkpoint class
pick test: add initial acceptance test
pick ci: ...
pick ci: ...
pick Merge ...
pick fix: avoid type widening ...
```
delete all of the lines except the commit that belongs to this PR (`pick fix: avoid type widening ...`), then do a `git push -f`.

Also happy to pair-program this in person if that would help!

**Comment by golnazmes** [comment]
> One other minor change: there are some duplicated commits in this PR. This is a common occurrence for projects using a `git rebase` workflow and is one of downsides to this particular workflow. Usually easy enough to fix:
> 
> ```shell
> git fetch upstream main
> git rebase -i upstream/main
> ```
> 
> these commands say:
> 
> 1. Download the changes from the upstream repo's main branch (amii-open-source/recommence), but don't do anything with them
> 2. Take those changes and rebase my current branch to be on top of those changes
> 
> When you do this, you will likely see a bunch of extra commits in the interactive rebase:
> 
> ```
> pick feat: add initial checkpoint class
> pick test: add initial acceptance test
> pick ci: ...
> pick ci: ...
> pick Merge ...
> pick fix: avoid type widening ...
> ```
> 
> delete all of the lines except the commit that belongs to this PR (`pick fix: avoid type widening ...`), then do a `git push -f`.
> 
> Also happy to pair-program this in person if that would help!


Thank you! i was wondering how I could clean the duplicate commits. I hope I did it right following your instructions. That would be great if we could do a review of how exactly this works later in person.

**Review by andnp — APPROVED** [review]

**Comment by andnp** [comment]
Nice, looks like it worked with the duplicated commits!

**Review by andy-amii — APPROVED** [review]
(oops wrong account haha)

**Pull request merged**
